# Generated by Django 4.1.3 on 2023-01-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDataBase',
            fields=[
                ('lab_station', models.CharField(max_length=100)),
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_station_id', models.IntegerField()),
                ('approved_status', models.BooleanField(default=False)),
                ('reservation_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.reservationdatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LabStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=10)),
                ('lab_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.reservationdatabase')),
            ],
        ),
    ]
