# Generated by Django 4.1.3 on 2023-01-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_reservationdatabase_lab_station_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdatabase',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationdatabase',
            name='start_date',
            field=models.DateField(),
        ),
    ]
