# Generated by Django 4.1.3 on 2023-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_reservationdatabase_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdatabase',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservationdatabase',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
