# Generated by Django 4.1.3 on 2023-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_reservationdatabase_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdatabase',
            name='lab_station',
            field=models.CharField(choices=[('1A', 'sala1'), ('2B', 'sala2'), ('3C', 'sala3'), ('4D', 'sala4')], max_length=100),
        ),
    ]
